[package]
name = "coroutine"
version = "0.1.7"
authors = [
    "Y. T. Chung <zonyitoo@gmail.com>",
    "Young.Wu <doomsplayer@gmail.com>",
    "Rustcc Developers"
]
license = "MIT/ISC"
repository = "https://github.com/rustcc/coroutine-rs"
description = "Coroutine Library in Rust"
readme = "README.md"
homepage = "https://github.com/rustcc/coroutine-rs"
build = "build.rs"
keywords = ["coroutine", "green", "thread", "fiber"]

[features]
default = [
    #"enable-locked-state",
]

enable-locked-state = [
    "spinlock"
]

[build-dependencies]
gcc = "*"
log = "*"

[lib]
name = "coroutine"
path = "src/lib.rs"

[dependencies]
mmap = "*"
#spinlocks = "*"

[dependencies.spinlock]
git = "https://github.com/zonyitoo/spinlock.rs.git"
optional = true

[dev-dependencies]
num_cpus = "*"
